//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LPGSavings.Resx.IntroForms.SecondStep {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SecondStepResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SecondStepResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("LPGSavings.Resx.IntroForms.SecondStep.SecondStepResources", typeof(SecondStepResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        internal static string AverageLPGPriceLabel {
            get {
                return ResourceManager.GetString("AverageLPGPriceLabel", resourceCulture);
            }
        }
        
        internal static string InstallationCostLabel {
            get {
                return ResourceManager.GetString("InstallationCostLabel", resourceCulture);
            }
        }
        
        internal static string SystemCapacityLabel {
            get {
                return ResourceManager.GetString("SystemCapacityLabel", resourceCulture);
            }
        }
        
        internal static string MaintenanceCostsLabel {
            get {
                return ResourceManager.GetString("MaintenanceCostsLabel", resourceCulture);
            }
        }
        
        internal static string FinishConfigurationButton {
            get {
                return ResourceManager.GetString("FinishConfigurationButton", resourceCulture);
            }
        }
    }
}
