//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LPGSavings.Resx.Insert.InsertFueling {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InsertFuelingResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InsertFuelingResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("LPGSavings.Resx.Insert.InsertFueling.InsertFuelingResource", typeof(InsertFuelingResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        internal static string OdometerLabel {
            get {
                return ResourceManager.GetString("OdometerLabel", resourceCulture);
            }
        }
        
        internal static string PriceLPGLabel {
            get {
                return ResourceManager.GetString("PriceLPGLabel", resourceCulture);
            }
        }
        
        internal static string LitersLPGLabel {
            get {
                return ResourceManager.GetString("LitersLPGLabel", resourceCulture);
            }
        }
        
        internal static string PricePBLabel {
            get {
                return ResourceManager.GetString("PricePBLabel", resourceCulture);
            }
        }
        
        internal static string LitersPBLabel {
            get {
                return ResourceManager.GetString("LitersPBLabel", resourceCulture);
            }
        }
        
        internal static string AdditionalInfoLabel {
            get {
                return ResourceManager.GetString("AdditionalInfoLabel", resourceCulture);
            }
        }
        
        internal static string HistoryLabel {
            get {
                return ResourceManager.GetString("HistoryLabel", resourceCulture);
            }
        }
        
        internal static string DateLabel {
            get {
                return ResourceManager.GetString("DateLabel", resourceCulture);
            }
        }
        
        internal static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
    }
}
